kind: Service
apiVersion: v1
metadata:
  name: qms-web-service
spec:
  selector:
    app: qms-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ztj-qms-web
  labels:
    app: qms-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qms-web
  template:
    metadata:
      labels:
        app: qms-web
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
